version: '3.8'
services:
  postgres-auth:
    image: postgres:latest
    container_name: bank-postgres-auth
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql
    networks:
      - bank-network

#  postgres-deposit:
#    image: postgres:latest
#    container_name: bank-postgres-deposit
#    environment:
#      POSTGRES_DB: deposit_service
#      POSTGRES_USER: deposit
#      POSTGRES_PASSWORD: deposit
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_deposit_data:/var/lib/postgresql
#    networks:
#      - bank-network

#  postgres-transaction:
#    image: postgres:latest
#    container_name: bank-postgres-transaction
#    environment:
#      POSTGRES_DB: transaction_service
#      POSTGRES_USER: transaction
#      POSTGRES_PASSWORD: transaction
#    ports:
#      - "5434:5432"
#    volumes:
#      - postgres_transaction_data:/var/lib/postgresql
#    networks:
#      - bank-network

#  redis:
#    image: redis:7-alpine
#    container_name: bank-redis
#    ports:
#      - "6379:6379"
#    networks:
#      - bank-network
#
#  config-server:
#    build: ./infrastructure/config-server
#    container_name: bank-config-server
#    ports:
#      - "8888:8888"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - bank-network
#
#  eureka-server:
#    build: ./infrastructure/eureka-server
#    container_name: bank-eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - bank-network
#    depends_on:
#      - config-server
#
#  auth-service:
#    build: ./auth-service
#    container_name: bank-auth-service
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - bank-network
#    depends_on:
#      - eureka-server
#      - postgres-auth  # ← своя БД
#      - redis

#  deposit-service:
#    build: ./deposit-service
#    container_name: bank-deposit-service
#    ports:
#      - "8082:8082"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - bank-network
#    depends_on:
#      - eureka-server
#      - postgres-deposit
#
#  transaction-service:
#    build: ./transaction-service
#    container_name: bank-transaction-service
#    ports:
#      - "8083:8083"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - bank-network
#    depends_on:
#      - eureka-server
#      - postgres-transaction
#      - redis
#
#  web-ui-service:
#    build: ./web-service
#    container_name: bank-web-ui
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
#    networks:
#      - bank-network
#    depends_on:
#      - eureka-server
#      - auth-service

volumes:
  postgres_auth_data:
#  postgres_deposit_data:
#  postgres_transaction_data:

networks:
  bank-network:
    driver: bridge